version: '3.8'

services:
  client:
    build: ./client_app
    image: inv_mgmt_client
    container_name: inv_mgmt_client_cont
    volumes:
      - ./client_app:/client
      - /client/node_modules
    ports:
      - 5173:5173
    depends_on:
      - server

  server:
    build: ./server
    image: inv_mgmt_server
    container_name: inv_mgmt_server_cont
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - 4000:4000
    env_file:
      - .env
    depends_on:
      pg_db:
        condition: service_healthy

  pg_db:
    image: postgres:latest
    container_name: inv_mgmt_db_cont
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
